### ISSUE TITLE
Option to load Files from the local disk of the raspberry, load/store settings to the raspberry

### ISSUE THREAD

**Issue by derFrickler** [andrewhodel/grblweb#11]
Very cool Project!
I will use it in my new Laserengraver build.

It would be very cool to be able to load gcode or svg files from the local disc of the rasbberry as well. 
storing and loading settings from the local raspberry disc would be very useful as well.

**Comment by danst0** [comment]
I second that, would be easier to use with a BitTorrent Sync based workflow
