### ISSUE TITLE
Change of tools

### ISSUE THREAD

**Issue by danst0** [andrewhodel/grblweb#17]
Hi,

how are you supposed to perform a tool change with GRBLweb?

I have M05 and M00 in my .nc file, then the machine halts, however no controls (eg. to lift Z) are possible.
Also I am not able to manually send commands.

Daniel

**Comment by andrewhodel** [comment]
This would be GRBL not GRBLWeb.

https://github.com/grbl/grbl/blob/master/grbl/gcode.c#L1077

**Comment by danst0** [comment]
However it would be great, if grblweb did not freeze on M00, so I could send commands to change the tool, redo zero and feed continue.
