### ISSUE TITLE
/dev/ttyAMA0 not showing up in Serial port list after making available

### ISSUE THREAD

**Issue by ghost** [andrewhodel/grblweb#2]
===Procedure to replicate issue===
Follow standard process to free up Raspberry pi serial port on your Pi Image (Procedure below)
Reboot to take effect

===Expected outcome:  ===
/dev/ttyAMA0 (Broadcom UART) available in list

===Actual Outcome:===
Serial port dropdown only shows "Select a Serial port"

Procedure to make /dev/AMA0 available:   Tested by using screen /dev/ttyAMA0 9600 and can communicate fine with Grbl on the GrblPi Shield, send commands, list settings etc from Screen.  Node is just not detecting it

Firstly, the kernel will use the port as controlled by kernel command line contained in /boot/cmdline.txt. The file will look something like this:

dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait

The console keyword outputs messages during boot, and the kgdboc keyword enables kernel debugging. You will need to remove all references to ttyAMA0. So, for the example above /boot/cmdline.txt, should contain:

dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait

You must be root to edit this (e.g. use sudo nano /boot/cmdline.txt). Be careful doing this, as a faulty command line can prevent the system booting.

```
Secondly, after booting, a login prompt appears on the serial port. This is controlled by the following lines in /etc/inittab:
```
# Spawn a getty on Raspberry Pi serial line

T0:23:respawn:/sbin/getty -L ttyAMA0 115200 vt100

You will need to edit this file to comment out the second line, i.e.
# T0:23:respawn:/sbin/getty -L ttyAMA0 115200 vt100

Finally you will need to reboot the Pi for the new settings to take effect. Once this is done, you can use /dev/ttyAMA0 like any normal linux serial port, and you wont get any unwanted traffic confusing the attached devices. )

**Comment by JosuaBlommie** [comment]
Hi,

I have posted almost everywhere I can yet no-one can provide a simple answer, or show me where I'm making mistakes or being stupid.

I'm using a RPi 2 B with Raspbian Jessie. I'm about to explode from what seems like a stupid issue.

I need the UART to communicate to a Pixhawk, and all the tutorials that show how to prepare the UART say you must disable the OS use of the serial port (through raspi-config, the GUI or removing all ttyAMA0 references in /boot/cmdline). However doing this removes the /dev/ttyAMA0 file completely, which in turn doesn't allow the UART to be used by the Pixhawk (through mavproxy). Enabling OS use of the serial port brings back the /dev/ttyAMA0 file, but UART doesn't communicate or operate correct when connected to RxTx on the Pixhawk.

PLEASE HELP!

This is the tutorial I followed: http://ardupilot.org/dev/docs/raspberry-pi-via-mavlink.html

**Comment by andrewhodel** [comment]
I'd get an ftdi cable and check that the serial output from the Pixhawk is
actually being sent, depending on the px4 flight stack or the ardupilot one
there are a lot of "parameters".

http://ardupilot.org/dev/_images/Pixhawk_FTDICable_NSH.jpg  Just connect it
to whatever port (telem1, telem2 or serial4/5) you have setup to output
Mavlink at the correct baud rate.


Andrew

**Comment by JosuaBlommie** [comment]
Looks like a known bug in the latest raspbian, easy to fix though.

These need to be done as the root user.

1. Disable "serial console" through GUI-preferences or "sudo raspi-config." Then reboot the pi.

2. Then change the following line in the file /boot/config.txt at the bottom of the file from:

enable_uart=0
to
enable_uart=1

2. Disable the ModemMonitor service by running the following command as root:

systemctl disable ModemManager.service

3. Then add youself to the dialout group, just to be sure you have the required permissions on the serial port:

adduser pi dialout

That should give you unrestricted proper access to the serial port.

Resources:
[url]https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=148515[/url]
and
[url]https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=82779[/url]

**Comment by deverejohn** [comment]
thanks, josua, EXACTLY what brought me here.

**Comment by JDHE** [comment]
Thanks Joshua, worked for me also. On rPi Zero.

**Comment by JosuaBlommie** [comment]
When past-me from almost a year ago saves present-me with exactly the same issue, I've never been so grateful to myself for posting the above answer on github. I'm also glad it helped other people.

**Comment by deverejohn** [comment]
I'm constantly having to start an OS config from scratch, and inevitably end up reading the same posts again and again.

On Mar 7, 2017, at 4:15 AM, Josua <notifications@github.com> wrote:

When past-me from almost a year ago saves present-me with exactly the same issue, I've never been so grateful to myself for posting the above answer on github. I'm also glad it helped other people.
