### ISSUE TITLE
Draggable jog interface is not good for fine control

### ISSUE THREAD

**Issue by thaytan** [andrewhodel/grblweb#21]
The draggable jog interface is OK for coarse movements, but relatively tricky for moving the head to a precise start position compared to the old buttons.

It would be nice to have an option to choose which UI to present.

The best I've used for this is the [pronterface UI](http://reprap.org/mediawiki/images/1/12/Pronterface.png) for 3D printing

**Comment by rulinups** [comment]
I support @thaytan. Need fine control, not fast and coarse movement.
As temprorary solution i use previously commit:
git chechout 4ce5de621
git checkout -b old_key_movement
