### ISSUE TITLE
nodejs serialport 1.4 is not compiling properly

### ISSUE THREAD

**Issue by itpmngt** [andrewhodel/grblweb#22]
Hi Andrew

nodejs serialport version 1.4.x is not compiling when doing a fresh 'npm install' (their issue) - I have changed version in package.json to "serialport" : "4.x" and voilá

BTW this is a great-great package, interesting solutions throughout the code, and millcrum is fantastic. If you want a hand on future developments drop a msg

Best,

**Comment by fluffy** [comment]
Thanks - I was having same problem

**Comment by andrewhodel** [comment]
Using 9.0.6 now.
