### ISSUE TITLE
Got error: connect ECONNREFUSED 127.0.0.1:8080 not enabling webcam

### ISSUE THREAD

**Issue by ProgrammerZ001** [andrewhodel/grblweb#33]
Using node js on window 10 
trying to run grblweb

config.webPort = 85;
config.serialBaudRate = 115200;
config.usettyAMA0 = 1;
// expects a webcam stream from mjpg_streamer
config.webcamPort = 8080;

my configurations

Got error: connect ECONNREFUSED 127.0.0.1:8080 not enabling webcam
![image](https://user-images.githubusercontent.com/41514826/90783380-7089fb80-e319-11ea-8736-7373a79e72aa.png)

**Comment by andrewhodel** [comment]
Did you read the part about mjpg_streamer?

You would have to port that to Windows to do what you want.

**Comment by ProgrammerZ001** [comment]
Thank you so much, Andrew, for such a quick response.
can please guide me a little bit
I am using mjpeg streamer by flyingorilla from the window store, will it do
the job, what I understand from reading is that I have to stream the USB
cam because node can get to do so. Am I right?
 thank and regards
Muhammad Zubair
software engineering student final year




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/20/20,
11:47:48 PM

**Comment by andrewhodel** [comment]
What are you trying to figure out?

Capture the MJPEG stream from mjpg_streamer running on linux using tcpdump
and then find a program that recreates the exact same protocol (http) and
file type (mjpeg) on windows.

Then point grblweb to that url.



Andrew

**Comment by andrewhodel** [comment]
This is why many people think Linux to be more useful than Windows.



Andrew
