### ISSUE TITLE
OS X serial connection, check permissions on /dev/cu.Bluetooth-Modem

### ISSUE THREAD

**Issue by smplman** [andrewhodel/grblweb#9]
I'm trying to run this in OS X and noticed that the server.js script loops over all of the available serial connections. This happens before the web server even gets up and running. On OS X it chokes on the bluetooth devices. I can edit the loop index to start at what ever the USB tty is running on and the script loads fine. I think there just needs to be some error catching when trying to initialize each serial connection. I have been looking into fixing this issue but wanted to make note of it here. 

Index hack line: https://github.com/andrewhodel/grblweb/blob/master/server.js#L89

```
speery@speerymbpx7:~/projects/grblweb (master)$ node server.js 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot open /dev/cu.Bluetooth-Modem
```

**Comment by winduptoy** [comment]
:+1:

**Comment by ewidance** [comment]
That's an OSX typycal problem. cu.Bluetooth-Incoming-Port  & cu.Bluetooth-Modem should be dropped from port enumeration list to allow port autodetect to work.
It could be a good idead to add a config.serialPort = "/dev/xxxx" in config.js, to force port name and passthru port detection.
